<?php

/** @var Magento\Catalog\Block\Product\View $block */
/** @var Magento\Framework\Escaper $escaper  */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Quote'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php echo $escaper->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number" name="qty" id="qty" maxlength="12"
                               value="<?php echo $block->getProductDefaultQty() * 1 ?>" title="<?php echo $escaper->escapeHtml(__('Qty')) ?>"
                               class="input-text qty" data-validate="{'required-number':true,digits:true}"/>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $escaper->escapeHtml($buttonTitle) ?>"
                        class="action toquote"
                        id="product-updatecart-button">
                    <span><?php echo $escaper->escapeHtml($buttonTitle) ?></span>
                </button>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "disableButton": {
                    "quoteButtonId": "#product-updatecart-button"
                }
            }
        }
    </script>
<?php endif; ?>
