<?php
/** @var $block QuoteMaster\QuoteStorm\Block\Product\View\View */
/** @var $escaper Magento\Framework\Escaper */
?>

<button id="product-addtoquote-button" type="submit" title="<?php echo __('Add to Quote') ?>" class="action toquote">
    <span><?php echo __('Add to Quote') ?></span>
</button>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {
                "catalogAddToCart": {
                    "addToQuoteFormAction": "<?php echo $escaper->escapeHtml($block->getAddToQuoteUrl()); ?>"
                }
            }
        }
    }
</script>


