
<?php
/** @var $block QuoteMaster\QuoteStorm\Block\Quote\Grid */
/** @var $escaper Magento\Framework\Escaper */
?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>

<form action="<?= $escaper->escapeUrl($block->getUrl('quote/quote/updateQuote')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"updateShoppingQuote":
              {"validationURL" : "<?= $escaper->escapeUrl($block->getUrl('quote/quote/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
      class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingQuote":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Quote Items')) ?></caption>
            <thead>
            <tr>
                <th class="col item" scope="col"><span><?= $escaper->escapeHtml(__('Item')) ?></span></th>
                <th class="col price" scope="col"><span><?= $escaper->escapeHtml(__('Price')) ?></span></th>
                <th class="col qty" scope="col"><span><?= $escaper->escapeHtml(__('Qty')) ?></span></th>
            </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $escaper->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $escaper->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $escaper->escapeHtml(__('Clear Quote')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= $escaper->escapeHtml(__('Clear Quote')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtml(__('Update Quote')) ?>"
                class="action update">
            <span><?= $escaper->escapeHtml(__('Update Quote')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('quotemaster.quote.order.actions') ?>
